-- Baseline: schema exatamente como estava apos ddl-auto:update ter criado
-- as tabelas incrementalmente (Fases 0-4). Gerado via pg_dump --schema-only
-- contra o banco de desenvolvimento e revisado a mao. A partir daqui, toda
-- mudanca de schema deve vir como uma nova migration V2, V3, ... (nunca
-- editar este arquivo depois de aplicado em algum ambiente).

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    nome_restaurante character varying(255) NOT NULL,
    senha character varying(255) NOT NULL,
    onboarding_concluido boolean DEFAULT false NOT NULL,
    margem_minima_esperada numeric(5,4) DEFAULT 0.20 NOT NULL,
    percentual_perda_alerta numeric(5,4) DEFAULT 0.05 NOT NULL,
    email_verificado boolean DEFAULT false NOT NULL,
    token_verificacao_email character varying(255),
    token_verificacao_expira_em timestamp(6) without time zone,
    token_verificacao_enviado_em timestamp(6) without time zone,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT uk_usuario_token_verificacao_email UNIQUE (token_verificacao_email)
);

CREATE TABLE assinatura (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criada_em timestamp(6) without time zone NOT NULL,
    plano character varying(255) NOT NULL,
    renova_em timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    stripe_customer_id character varying(255),
    stripe_subscription_id character varying(255),
    usuario_id bigint NOT NULL,
    CONSTRAINT assinatura_plano_check CHECK (((plano)::text = ANY ((ARRAY['GRATIS'::character varying, 'PRO'::character varying])::text[]))),
    CONSTRAINT assinatura_status_check CHECK (((status)::text = ANY ((ARRAY['ATIVA'::character varying, 'INADIMPLENTE'::character varying, 'CANCELADA'::character varying])::text[]))),
    CONSTRAINT uk_assinatura_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_assinatura_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE conversa_chat (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iniciada_em timestamp(6) without time zone,
    usuario_id bigint NOT NULL,
    CONSTRAINT fk_conversa_chat_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE mensagem_chat (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autor character varying(255) NOT NULL,
    conteudo oid NOT NULL,
    enviada_em timestamp(6) without time zone NOT NULL,
    conversa_id bigint NOT NULL,
    CONSTRAINT mensagem_chat_autor_check CHECK (((autor)::text = ANY ((ARRAY['USUARIO'::character varying, 'IA'::character varying])::text[]))),
    CONSTRAINT fk_mensagem_chat_conversa FOREIGN KEY (conversa_id) REFERENCES conversa_chat(id)
);

CREATE TABLE documento_conhecimento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em timestamp(6) without time zone NOT NULL,
    fonte character varying(255),
    titulo character varying(255) NOT NULL
);

CREATE TABLE trecho_conhecimento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conteudo oid NOT NULL,
    embedding public.vector(1024),
    ordem integer NOT NULL,
    documento_id bigint NOT NULL,
    CONSTRAINT fk_trecho_conhecimento_documento FOREIGN KEY (documento_id) REFERENCES documento_conhecimento(id)
);

CREATE TABLE upload_planilha (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enviado_em timestamp(6) without time zone NOT NULL,
    mensagem_erro character varying(255),
    nome_arquivo_original character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    tipo character varying(255) NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT upload_planilha_status_check CHECK (((status)::text = ANY ((ARRAY['PROCESSANDO'::character varying, 'PROCESSADO'::character varying, 'ERRO'::character varying])::text[]))),
    CONSTRAINT upload_planilha_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['VENDAS'::character varying, 'ESTOQUE'::character varying])::text[]))),
    CONSTRAINT fk_upload_planilha_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE item_venda (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custo_unitario numeric(12,2),
    data date,
    nome_prato character varying(255) NOT NULL,
    preco_venda numeric(12,2) NOT NULL,
    quantidade_vendida integer NOT NULL,
    upload_id bigint NOT NULL,
    CONSTRAINT fk_item_venda_upload FOREIGN KEY (upload_id) REFERENCES upload_planilha(id)
);

CREATE TABLE item_estoque (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custo_unitario numeric(12,2) NOT NULL,
    data date,
    nome_insumo character varying(255) NOT NULL,
    quantidade_comprada numeric(12,3) NOT NULL,
    quantidade_perdida numeric(12,3),
    upload_id bigint NOT NULL,
    CONSTRAINT fk_item_estoque_upload FOREIGN KEY (upload_id) REFERENCES upload_planilha(id)
);

CREATE TABLE relatorio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmv_calculado numeric(7,4),
    conteudo_textoia text NOT NULL,
    gerado_em timestamp(6) without time zone NOT NULL,
    upload_estoque_id bigint,
    upload_vendas_id bigint,
    usuario_id bigint NOT NULL,
    CONSTRAINT fk_relatorio_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_relatorio_upload_vendas FOREIGN KEY (upload_vendas_id) REFERENCES upload_planilha(id),
    CONSTRAINT fk_relatorio_upload_estoque FOREIGN KEY (upload_estoque_id) REFERENCES upload_planilha(id)
);

CREATE TABLE indicador_prato (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alerta boolean NOT NULL,
    margem_calculada numeric(7,4) NOT NULL,
    nome_prato character varying(255) NOT NULL,
    relatorio_id bigint NOT NULL,
    CONSTRAINT fk_indicador_prato_relatorio FOREIGN KEY (relatorio_id) REFERENCES relatorio(id)
);
