-- Geracao/edicao de imagem de prato via IA (plano PRO — docs/06-geracao-imagem-ia.md).
-- O binario da imagem fica em disco (restoria.imagem.storage-dir); aqui so
-- os metadados e a referencia ao arquivo.
CREATE TABLE imagem_prato (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL,
    prompt text NOT NULL,
    tipo_operacao character varying(255) NOT NULL,
    imagem_original_caminho character varying(255),
    caminho_arquivo character varying(255) NOT NULL,
    criada_em timestamp(6) without time zone NOT NULL,
    CONSTRAINT imagem_prato_tipo_operacao_check CHECK (((tipo_operacao)::text = ANY ((ARRAY['GERACAO'::character varying, 'EDICAO'::character varying])::text[]))),
    CONSTRAINT fk_imagem_prato_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);
