-- Contador de uso por usuario e mes (competencia 'AAAA-MM'), fonte de verdade
-- do limite do plano (ver LimiteUsoService). Substitui a contagem direta em
-- mensagem_chat/relatorio/imagem_prato, que deixava requisicoes simultaneas
-- passarem todas na verificacao.
CREATE TABLE uso_mensal (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL,
    competencia character varying(7) NOT NULL,
    mensagens integer NOT NULL DEFAULT 0,
    relatorios integer NOT NULL DEFAULT 0,
    imagens integer NOT NULL DEFAULT 0,
    CONSTRAINT uk_uso_mensal_usuario_competencia UNIQUE (usuario_id, competencia),
    CONSTRAINT fk_uso_mensal_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- Carrega o uso ja feito no mes corrente, para ninguem ganhar cota nova com a
-- troca de mecanismo. Timestamps sao gravados no horario de Sao Paulo.
WITH inicio AS (
    SELECT date_trunc('month', now() AT TIME ZONE 'America/Sao_Paulo') AS mes
)
INSERT INTO uso_mensal (usuario_id, competencia, mensagens, relatorios, imagens)
SELECT u.id,
       to_char((SELECT mes FROM inicio), 'YYYY-MM'),
       (SELECT count(*) FROM mensagem_chat m JOIN conversa_chat c ON c.id = m.conversa_id
         WHERE c.usuario_id = u.id AND m.autor = 'USUARIO' AND m.enviada_em >= (SELECT mes FROM inicio)),
       (SELECT count(*) FROM relatorio r
         WHERE r.usuario_id = u.id AND r.gerado_em >= (SELECT mes FROM inicio)),
       (SELECT count(*) FROM imagem_prato i
         WHERE i.usuario_id = u.id AND i.criada_em >= (SELECT mes FROM inicio))
FROM usuario u;
