-- item_venda / item_estoque passam a gerar id por SEQUENCE (allocationSize 50
-- no Hibernate) em vez de IDENTITY, para permitir INSERT em lote no upload de
-- planilha. A coluna continua "GENERATED BY DEFAULT AS IDENTITY", que aceita
-- id explicito; as sequences comecam depois do maior id ja existente.
CREATE SEQUENCE item_venda_seq INCREMENT BY 50;
SELECT setval('item_venda_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM item_venda));

CREATE SEQUENCE item_estoque_seq INCREMENT BY 50;
SELECT setval('item_estoque_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM item_estoque));
